### ISSUE TITLE
您好，作者，我想问下这个日历组件是还在迭代更新功能中，还是已经稳定？

### ISSUE THREAD

**Issue by CasualMing** [wangdaodao/vue-lunar-calendar-pro#15]
您好，作者，我想问下这个日历组件是还在迭代更新功能中，还是已经稳定？
如果是已经稳定，那么我看文档中是提供了slot插槽，那组件向外暴露了哪些插槽，能在文档中补充一下嘛？
如果是还在更新迭代中，那有计划，计划之后新增哪些功能，哪些功能会优化嘛？

**Comment by wangdaodao** [comment]
你好，这个日历组件基本上处于稳定阶段，但是我会持续关注bug修复。至于插槽，我后续补充下文档，谢谢关注。

**Comment by CasualMing** [comment]
> 你好，这个日历组件基本上处于稳定阶段，但是我会持续关注bug修复。至于插槽，我后续补充下文档，谢谢关注。

引入组件的时候也需要更新一下，按照你那文档引入，我还以为样式在内部已经引用，结果只是引入了功能文件，样式文件还需要另外引入。

**Comment by wangdaodao** [comment]
> 
> 
> > 你好，这个日历组件基本上处于稳定阶段，但是我会持续关注bug修复。至于插槽，我后续补充下文档，谢谢关注。
> 
> 引入组件的时候也需要更新一下，按照你那文档引入，我还以为样式在内部已经引用，结果只是引入了功能文件，样式文件还需要另外引入。

文档已经更新，另外插槽这块也补充了。
