### ISSUE TITLE
天干地支的月份好像有问题

### ISSUE THREAD

**Issue by MrTan123** [wangdaodao/vue-lunar-calendar-pro#7]
如2020-11-7日是庚子鼠年 丁亥月 甲寅日      我们的计算结果是庚子鼠年 丙戌月 甲寅日

**Comment by wangdaodao** [comment]
> 
> 
> 如2020-11-7日是庚子鼠年 丁亥月 甲寅日 我们的计算结果是庚子鼠年 丙戌月 甲寅日

感谢，这块里面的代码采用的是https://github.com/jjonline/calendar.js/blob/master/calendar.js，我抽时间修复一下。

**Comment by wangdaodao** [comment]
> 
> 
> 如2020-11-7日是庚子鼠年 丁亥月 甲寅日 我们的计算结果是庚子鼠年 丙戌月 甲寅日

庚子年 【鼠年】丁亥月 甲寅日，我百度了下日历，应该是你计算出错了。

**Comment by wangdaodao** [comment]
和百度的日历对比了一下，没有太大问题，我先关闭了。如果发现问题，可以先跑下https://blog.wangdaodao.com/vue-lunar-calendar-pro/example/demo7.html  这个demo，然后和百度的日历做下对比。
